#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dtopt
Version  : 0.1
Release  : 6
URL      : https://files.pythonhosted.org/packages/ba/2c/e012086b9f515110a31bbd3e78a509e2b968e0f6808d219c178c5ae697f7/dtopt-0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ba/2c/e012086b9f515110a31bbd3e78a509e2b968e0f6808d219c178c5ae697f7/dtopt-0.1.tar.gz
Summary  : Add options to doctest examples while they are running
Group    : Development/Tools
License  : MIT
Requires: dtopt-python3
Requires: dtopt-python
BuildRequires : buildreq-distutils3

%description
When using the `doctest

%package python
Summary: python components for the dtopt package.
Group: Default
Requires: dtopt-python3

%description python
python components for the dtopt package.


%package python3
Summary: python3 components for the dtopt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dtopt package.


%prep
%setup -q -n dtopt-0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536442362
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
